#!/bin/bash
icon="$HOME/.local/share/backgrounds/2022-06-10-14-28-37-forest.jpg"
# create a temp file
img=$(mktemp /tmp/XXXXXXXXXX.png)
# Take a screenshot of current desktop
import -window root $img 


# use the below command to genrate blur images
convert in-img.png -blur 0x25 out-img.png



# Run i3lock with custom background
i3lock -i $img
# Remove the tmp file
rm $img
