---
- name: Download go tar file
  vars:
    go_version: 1.22.3
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz
    dest: /tmp/go{{go_version}}.linux-amd64.tar.gz
  tags: golang

- name: check if the go installation is there or not
  tags: golang
  stat:
    path: "/usr/local/go"
  register: previous_go_installation

- name: Delete previous installation
  tags: golang
  when: previous_go_installation.stat.exists
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
    force: true

- name: Extract and move new go folder to /usr/local
  vars:
    go_version: 1.22.3
  tags: golang
  ansible.builtin.unarchive:
    src: /tmp/go{{go_version}}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Delete downloaded tar file
  vars:
    go_version: 1.22.3
  tags: golang
  ansible.builtin.file:
    path: /tmp/go{{go_version}}.linux-amd64.tar.gz*
    state: absent
    force: true

- name: Add go binary path to ~/.zshrc
  tags: golang
  lineinfile:
    path: ~/.zshrc
    line: "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin"
    state: present
