export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gnzh"

NPM_CONFIG_PREFIX='~/.npm-global'

plugins=(
    git
    kubectl
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"


alias l='ls -l'
alias la='ls -la'
alias gpo='git push origin'
alias gplo='git pull origin'
alias g='git'
alias gcs='git commit -s'
alias cls='clear'

alias vi='nvim'

alias d=docker

export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/go/bin"


alias ls='lsd'

alias pynbtopdf='jupyter-nbconvert --to pdf'


export GPG_TTY=$(tty)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"

export PATH="$PATH:$HOME/.protobuff/bin"

alias curlx="curl -X GET -IL"

